### ISSUE TITLE
strange message in mkeyb 0.46 and 0.48

### ISSUE THREAD

**Issue by fritzmueller** [davidebreso/mkeyb#1]
Hi, I noticed a strange message at both versions of mkeyb (0.46 and 0.48 -I did not test older versions) in vmware, virtualbox, qemu AND on an old real laptop.

First scenario: mkeyb is NOT loaded at fdauto.bat:
type mkeyb us and you will get the message: US keyboards don't need a keyboard handler. (so far ok).
Different versions of keyb found b0f003c  !=b03c003c
I get the same message when I run mkeyb /u after this message.
I do not get this message when loading / unloading gr or it language.

Second scenario:
I reboot, and mkeyb gr (same with it) IS loaded at fdauto.bat:
when I enter mkeyb /u I also get the message mentioned above.

Thanks for reading and checking.

**Comment by davidebreso** [comment]
That message should appear only if a different version of mKEYB is already installed in memory. Does MEM /C lists any instance of mKEYB installed before you run it?

I cannot replicate your scenario unless I have a different version loaded in memory. I am using FreeDOS 1.3, here, what dos are you using?
Please consider that FreeDOS includes a previous version of mKEYB in FREEDOS\BIN

**Comment by fritzmueller** [comment]
Hi, I just tested once again as I know that it is always hard to understand if it cannot be reproduced. So I tried to create a diskette for you (everything with FreeDOS 1.3 files) with kernel, command, edit, fdconfig, config, fdauto and autoexec. bat.
The reported message did NOT appear.
Then I installed a new FreeDOS 1.3 live on VirtualBox with the following settings: german language and italian keyboard layout.
In fdauto.bat german language and mkeyb it (0.46) were set. Only basic installation.
This time I got the message: mkeyb 0.46 diffent versions of keyb found 642003c != b03c003c.
I mounted the virtual machine, renamed mkeyb to mkeyb046.exe, copied mkeyb 0.48 to c:\freedos\bin and renamed it mkeyb048.exe so that I have both files inside c:\fdos\bin. Then I edited c:\fdauto.bat and replaced "mkeyb it" by "mkeyb048 it".
I hope you can reproduce it now.
![italian keyboard04](https://user-images.githubusercontent.com/43041549/162454637-8a8533d8-983f-42a4-9817-9f21b5c8e57b.png)
![italian keyboard05](https://user-images.githubusercontent.com/43041549/162455379-46d1b89d-4768-4049-871d-0f8bcf523bcb.png)

**Comment by davidebreso** [comment]
Now I can reproduce it, thanks. The strange message appears because FDAUTO.BAT loads additional drivers after mMEYB. Some of them, namely FDAPM and the cd-rom driver, get into the way and prevent unloading of mKEYB. 
In this case the old instance of mKEYB is disabled, but kept in memory, and a new copy of mKEYB is installed. 

If you move "mkeyb048.exe IT" at the end of the file after the :END label, then mKEYB is the last driver to be loaded, and so it can be uninstalled, and the message disappear.

I understand that a better error message is needed. Also, the code that checks if mKEYB can be uninstalled may fail in some cases, so a better sanity check is needed here.

**Comment by fritzmueller** [comment]
Hi, I forgot to share the following information with you:
I promised Tom Ehlert earlier this year that I will donate 300 Euros to a charity if the Turkish keyboard support is built into mkeyb. A donation from Ärzte ohne Grenzen (Medecines sans frontiers, Doctors Without Borders) was planned. The offer still stands. Of course we can talk about another charity company.

**Comment by davidebreso** [comment]
[Pre-release 0.49a](https://github.com/davidebreso/mkeyb/releases/tag/v0.49a) fixes the installation check message bug.

I can try to add the Turkish keyboard, but I need a reference to the layout. Is this a good one?

http://kbdlayout.info/kbdtuq

Also, what is the standard codepage for turkish in DOS?

**Comment by cardpuncher** [comment]
Hi, just got Fritz's mail and thought I'd answer here.

The standard codepage for Turkish in DOS is IBM CP 857. And like he said, there are two keyboard layouts in use in Turkey, one derived from QWERTY, used by the huge majority of typists (including yours truly :), and another one, called the F layout, optimized for typing efficiently and quickly.

The link you provided depicts correctly the Q layout and for the F layout, you may want to take a look at <http://kbdlayout.info/kbdtuf>. There's more information about it on <https://en.wikipedia.org/wiki/Keyboard_layout#Turkish_(F-keyboard)>.

**Comment by davidebreso** [comment]
> Hi, just got Fritz's mail and thought I'd answer here.

Thanks! I check what I can do about it, and ask you and Fritz to test the layouts when they will be ready.

I opened a new issue to track the development of Turkish layout at https://github.com/davidebreso/mkeyb/issues/2, plase follow up there.

**Comment by fritzmueller** [comment]
Hi,

I only have a bad internet connection here, so I cannot download the final live CD 1.3, but Berki remembered me some days ago that FD 1.3 live offers both Turkish F and Q.

I only have a RC version of FD live 1.3 here.

This is the difference:

 


turkish F:
keyb TR,857,%DOSDIR%\BIN\KEYBRD2.SYS /ID:440

turkish Q:
keyb TR,857,%DOSDIR%\BIN\KEYBRD2.SYS

 

Please check with original live CD 1.3 as I remember that there were problems with path for these two keyboard layouts at the first RC (something like %DOSDIRBINKEYBRD2.SYS).

 

Willi


 
 

Sent: Saturday, April 16, 2022 at 11:02 AM
