### ISSUE TITLE
Feature request: option to disable loading high

### ISSUE THREAD

**Issue by Korkman** [davidebreso/mkeyb#4]
I have this game Pushover which crashes when the keyboard driver is loaded into high memory (both vanilla keyb and mkeyb). I guess mkeyb could be made compatible with a flag /m or so which disables loading into high memory.

**Comment by davidebreso** [comment]
Thank you @Korkman. The game do not work on my machine (it crashes even with no drivers loaded), but the option may be useful in other scenario. Release v0.51 adds support for the flag and your german layouts.
