### ISSUE TITLE
CTRL+Z/Y incorrect

### ISSUE THREAD

**Issue by Ohrwerk** [davidebreso/mkeyb#5]
I use mkeyb 0.40 [Feb 14 2005], this is the only working version for me.
https://web.archive.org/web/20060429033928/http://www.drivesnapshot.de/freedos/mkeyb.zip

If i use newer versions, all is working fine. But IF i DO a COPY CON TEST.TXT command and want to save my file with CTRL+Z,
then MKEYB makes a ^Y. I must use CTRL+Y do get a ^Z to save may file and close COPY CON.
Tested versions: 0.43, 0.46, 0.48 0.50, 0.51 all failed.
Configuration:
Virtual System: 86Box 3.7.1 (4032), System i430FX ASUS P/I-P54TP4XE P120, PCI S3 Trio64 (PHOENIX) 
MKEYB: C:\TEST\MKEYB.EXE GR

Happy Coding

**Comment by davidebreso** [comment]
Hi @Ohrwerk Ohrwerk, thanks for spotting the bug. It affects also french layouts, where CTRL+Z produces ^W.
Commit 0b24770 is a tentative fix of the problem. Please let me know if the following version of MKEYB works: [mkeyb.exe](https://github.com/davidebreso/mkeyb/raw/0b247700c1e3dcdb00b494f4f00babddf596b423/mkeyb.exe)

**Comment by davidebreso** [comment]
Release v0.52 includes the bugfix and closes the issue.

**Comment by Ohrwerk** [comment]
i have to thank, it makes me happy that there are still programmers who make something for DOS.
